### ISSUE TITLE
Tracemap validation cannot handle shapefiles with z coordinates

### ISSUE THREAD

**Issue by Siyh** [nialov/fractopo#21]
Validation (`Validation(...).run_validation()`) fails with `TypeError: within_bounds() takes 6 positional arguments but 7 were given` if the tracemap shapefiles read by geopandas contain z coordinates.

I worked around this by removing the z coordinate prior to validation using this code:

```
from shapely.geometry import Polygon, MultiPolygon, LineString

class_lookup = dict(Polygon=Polygon, MultiPolygon=MultiPolygon, LineString=LineString)


def remove_z_coordinates(geometries):
    """
    :param geometries: Shapely geometry iterable
    :return: a list of Shapely geometries without z coordinates
    """
    return [shapely.wkb.loads(shapely.wkb.dumps(geometry, output_dimension=2)) for geometry in geometries]


trace_data.geometry = remove_z_coordinates(trace_data.geometry)
```

In case something similar is your preferred fix.

Thanks for developing a great tool!

Edit:  Simpler solution from one of the comments [here](https://gist.github.com/rmania/8c88377a5c902dfbc134795a7af538d8)

**Comment by nialov** [comment]
Thank you a lot for the issue report! I probably have not ever tested geometries with z-coordinates in `fractopo` so the validation functionality might not be the only part where the issue might arise! I will fix the issue shortly.

If you have any additional problems do not hesitate to create more issues, they are very helpful for me to iron out user problems that I have not thought of.
