### ISSUE TITLE
Error when plotting trace lengths

### ISSUE THREAD

**Issue by lachlangrose** [nialov/fractopo#25]
Hi,

I'm just starting my review of the code for JOSS.

I'm using a google colab environment and have installed fractopo using `pip install git+https://github.com/nialov/fractopo` - so this should be the most recent version of the code.

I have tried to run your example https://fractopo.readthedocs.io/en/latest/notebooks/fractopo_network_1.html but I am getting a matplotlib error.

```
ValueError                                Traceback (most recent call last)
[<ipython-input-12-a892d99a2aba>](https://localhost:8080/#) in <cell line: 1>()
----> 1 fit, fig, ax = kb11_network.plot_trace_lengths()

5 frames
[/usr/local/lib/python3.9/dist-packages/matplotlib/axis.py](https://localhost:8080/#) in set_ticks(self, ticks, labels, minor, **kwargs)
   2070         """
   2071         if labels is None and kwargs:
-> 2072             raise ValueError('labels argument cannot be None when '
   2073                              'kwargs are passed')
   2074         result = self._set_tick_locations(ticks, minor=minor)

ValueError: labels argument cannot be None when kwargs are passed
```

I'm using matplotlib 3.7.1. and have a gist here if you want to try running it https://gist.github.com/lachlangrose/506df31fdd81019df4a7e1d5126cac40

**Comment by nialov** [comment]
Thank you for the report! Based on short testing it it related to the newer `matplotlob` version. 3.6.3 is the `matplotlib` version used in development that is locked in `poetry.lock`. I will issue a fix of either constraining the `matplotlib` version in `pyproject.toml` that `pip` uses for installs or fixing the actual code to support the newer version.

Until I have issued a fix you can specify the version like so in the notebook:

~~~
!pip install git+https://github.com/nialov/fractopo matplotlib==3.6.3
~~~

**Comment by nialov** [comment]
Pull request #27 was merged which should fix this specific issue. The notebook you included in your gist now works. If the same issue persists on your end you can report it here! I will close this after a week or two otherwise.

**Comment by lachlangrose** [comment]
Thanks, this fixed the issue.
