### ISSUE TITLE
[paper] proposition for summary

### ISSUE THREAD

**Issue by dglaeser** [nialov/fractopo#38]
At the end of the summary, it says

"
To analyze these datasets, common Geographic Information System (GIS) tools are typically used to perform geospatial operations and analysis of the data. However, these tools are not specialized to handle the specific requirements for geometric and topological consistency of the fracture trace data. Therefore, it is both convenient and beneficial for users to have access to a common workflow, provided by the newly developed fractopo package, for the data validation and analysis, rather than implementing a geospatial analysis separately each time for the data.
"

This is just a semantic thing, but I don't understand the causality between the first two sentences and the last one. The way I understand the first two, GIS tools are __missing__ functionality for checking fracture trace data consistency. But the last sentence says that because of that, it's good to have access to a _common workflow_. Here, I would have rather expected something along the lines that `fractopo` seeks to close this gap. Also, I cannot relate the last argument - "rather than implementing a geospatial analysis separately each time for the data." - to the stuff said before. This means the analysis __can__ be done in GIS tools but I have to _implement_ it again for each data? (That is, the tools don't allow to define an analysis pipeline in which I can just swap the input data?)

 I have the feeling that two points are intermingled here and it may be more clear if they were laid out separately:

1. `fractopo` provides missing functionality in typical GIS tools (for the validation part) 
2. `fractopo` provides both validation & analysis in one package, usable outside of GIS tools (e.g. in scripts). This enables users to script their analysis pipeline once and send through different data as desired

Is this correct? In case I am getting it all wrong, my apologies in advance...

**Comment by nialov** [comment]
The compiled pdf with changes is available as an actions artifact here: https://github.com/nialov/fractopo/suites/12516824701/artifacts/668015303

I separated the summary into two paragraphs as well, hopefully appropriate.

**Comment by dglaeser** [comment]
looks good to me, thank you!

**Comment by dglaeser** [comment]
feel free to close this with merging #43
